# Generated by Django 4.2.7 on 2025-11-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colaborador', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='ambulancias.ambulancia')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stockMinimo', models.IntegerField()),
                ('stock_actual', models.IntegerField(default=0)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('unidadMedida', models.CharField(choices=[('unidades', 'Unidades'), ('paquetes', 'Paquetes'), ('pares', 'Pares')], default='unidades', max_length=20)),
                ('tipoAmbulancia', models.CharField(choices=[('tipo_1', 'Tipo 1'), ('tipo_2', 'Tipo 2'), ('tipo_3', 'Tipo 3')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.insumomedico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.IntegerField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.checklist')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.insumomedico')),
            ],
        ),
    ]
