# Generated by Django 4.2.7 on 2025-11-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('preparada', 'Preparada'), ('en_proceso', 'En proceso'), ('inhabilitada', 'Inhabilitada')], default='en_proceso', max_length=20)),
                ('tipo_A', models.CharField(choices=[('tipo_1', 'Tipo 1'), ('tipo_2', 'Tipo 2'), ('tipo_3', 'Tipo 3')], max_length=10)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_combustible', models.DateField()),
                ('comb_inicial', models.IntegerField()),
                ('comb_final', models.IntegerField()),
                ('km_inicial', models.IntegerField()),
                ('km_final', models.IntegerField()),
                ('nombre_colaborador', models.CharField(max_length=100)),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible', to='ambulancias.ambulancia')),
            ],
        ),
        migrations.CreateModel(
            name='Avería',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoF', models.CharField(choices=[('critico', 'Crítico'), ('grave', 'Grave'), ('leve', 'Leve')], max_length=10)),
                ('descripcion_averia', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('nombre_colaborador', models.CharField(max_length=100)),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averias', to='ambulancias.ambulancia')),
            ],
        ),
    ]
