# Generated by Django 4.2.7 on 2025-11-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('inventarios', '0001_initial'),
        ('ambulancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado')], max_length=50)),
                ('nombre_chofer', models.CharField(max_length=100)),
                ('paciente_opcional', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulancias.ambulancia')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimientos', models.TextField()),
                ('pertenencias', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('informe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emergencias.informeemergencia')),
            ],
        ),
        migrations.CreateModel(
            name='ReportePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='emergencias.reporteemergencia')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.insumomedico')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='emergencias.reporteemergencia')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoRevocacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_declarante', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(choices=[('paciente', 'Paciente'), ('responsable', 'Responsable Legal')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carnet de extranjería'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('motivo_revocacion', models.TextField()),
                ('nombre_testigo', models.CharField(max_length=100)),
                ('fecha_firma', models.DateField(auto_now_add=True)),
                ('informe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emergencias.informeemergencia')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoConsentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('dni_paciente', models.CharField(max_length=12)),
                ('personal_medico', models.CharField(max_length=100)),
                ('acepta_acto_medico', models.BooleanField(default=False)),
                ('acepta_traslado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateField(auto_now_add=True)),
                ('informe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emergencias.informeemergencia')),
            ],
        ),
    ]
